CREATE DATABASE zohan_tech_store;
USE zohan_tech_store;

-- ==============================
-- MODULO ESTADO
-- ==============================

CREATE TABLE ESTADO_TB (
    ID_ESTADO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL
);

-- ==============================
-- MODULO DIRECCION
-- ==============================

CREATE TABLE PAIS_TB (
    ID_PAIS INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_PAIS VARCHAR(100),
    ID_ESTADO INT,
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO_TB(ID_ESTADO)
);

CREATE TABLE PROVINCIA_TB (
    ID_PROVINCIA INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_PROVINCIA VARCHAR(100),
    ID_PAIS INT,
    ID_ESTADO INT,
    FOREIGN KEY (ID_PAIS) REFERENCES PAIS_TB(ID_PAIS),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO_TB(ID_ESTADO)
);

CREATE TABLE CANTON_TB (
    ID_CANTON INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_CANTON VARCHAR(100),
    ID_PROVINCIA INT,
    ID_ESTADO INT,
    FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIA_TB(ID_PROVINCIA),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO_TB(ID_ESTADO)
);

CREATE TABLE DISTRITO_TB (
    ID_DISTRITO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_DISTRITO VARCHAR(100),
    ID_CANTON INT,
    ID_ESTADO INT,
    FOREIGN KEY (ID_CANTON) REFERENCES CANTON_TB(ID_CANTON),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO_TB(ID_ESTADO)
);

CREATE TABLE DIRECCION_TB (
    ID_DIRECCION INT AUTO_INCREMENT PRIMARY KEY,
    ID_DISTRITO INT,
    DETALLES TEXT,
    ID_ESTADO INT,
    FOREIGN KEY (ID_DISTRITO) REFERENCES DISTRITO_TB(ID_DISTRITO),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO_TB(ID_ESTADO)
);

-- ==============================
-- MODULO USUARIO
-- ==============================

CREATE TABLE TIPO_USUARIO_TB (
    ID_TIPO_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100),
    ID_ESTADO INT,
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO_TB(ID_ESTADO)
);

CREATE TABLE USUARIO_TB (
    IDENTIFICACION VARCHAR(20) PRIMARY KEY,
    NOMBRE VARCHAR(100),
    APELLIDO_PATERNO VARCHAR(100),
    APELLIDO_MATERNO VARCHAR(100),
    FECHA_REGISTRO DATETIME DEFAULT CURRENT_TIMESTAMP,
    ID_DIRECCION INT,
    ID_TIPO_USUARIO INT,
    ID_ESTADO INT,
    FOREIGN KEY (ID_DIRECCION) REFERENCES DIRECCION_TB(ID_DIRECCION),
    FOREIGN KEY (ID_TIPO_USUARIO) REFERENCES TIPO_USUARIO_TB(ID_TIPO_USUARIO),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO_TB(ID_ESTADO)
);

CREATE TABLE CORREO_TB (
    IDENTIFICACION VARCHAR(20),
    CORREO VARCHAR(150) UNIQUE NOT NULL,
    ID_ESTADO INT,
    PRIMARY KEY (IDENTIFICACION, CORREO),
    FOREIGN KEY (IDENTIFICACION) REFERENCES USUARIO_TB(IDENTIFICACION),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO_TB(ID_ESTADO)
);

CREATE TABLE TELEFONO_TB (
    IDENTIFICACION VARCHAR(20),
    TELEFONO VARCHAR(20) UNIQUE NOT NULL,
    ID_ESTADO INT,
    PRIMARY KEY (IDENTIFICACION, TELEFONO),
    FOREIGN KEY (IDENTIFICACION) REFERENCES USUARIO_TB(IDENTIFICACION),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO_TB(ID_ESTADO)
);

-- ==============================
-- MODULO CUENTA
-- ==============================

CREATE TABLE CUENTA_TB (
    ID_CUENTA INT AUTO_INCREMENT PRIMARY KEY,
    IDENTIFICACION VARCHAR(20),
    USERNAME VARCHAR(100) UNIQUE,
    PASSWORD VARCHAR(255),
    INTENTOS_FALLIDOS INT DEFAULT 0,
    ULTIMO_LOGIN DATETIME,
    ID_ESTADO INT,
    FOREIGN KEY (IDENTIFICACION) REFERENCES USUARIO_TB(IDENTIFICACION),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO_TB(ID_ESTADO)
);

-- ==============================
-- MODULO PRODUCTOS
-- ==============================

CREATE TABLE CATEGORIA_TB (
    ID_CATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100),
    ID_ESTADO INT,
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO_TB(ID_ESTADO)
);

CREATE TABLE MARCA_TB (
    ID_MARCA INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100),
    ID_ESTADO INT,
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO_TB(ID_ESTADO)
);

CREATE TABLE PRODUCTO_TB (
    ID_PRODUCTO INT AUTO_INCREMENT PRIMARY KEY,
    SKU VARCHAR(50) NOT NULL UNIQUE,
    NOMBRE VARCHAR(150),
    DESCRIPCION TEXT,
    PRECIO DECIMAL(10,2),
    STOCK_MINIMO INT DEFAULT 0,
    ID_CATEGORIA INT,
    ID_MARCA INT,
    ID_ESTADO INT,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA_TB(ID_CATEGORIA),
    FOREIGN KEY (ID_MARCA) REFERENCES MARCA_TB(ID_MARCA),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO_TB(ID_ESTADO)
);

CREATE TABLE PRODUCTO_IMAGE_TB (
    ID_IMAGEN INT AUTO_INCREMENT PRIMARY KEY,
    ID_PRODUCTO INT,
    URL_IMAGE VARCHAR(255),
    ID_ESTADO INT,
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO_TB(ID_PRODUCTO),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO_TB(ID_ESTADO)
);

CREATE TABLE COMENTARIO_TB (
    ID_COMENTARIO INT AUTO_INCREMENT PRIMARY KEY,
    ID_PRODUCTO INT,
    IDENTIFICACION VARCHAR(20),
    CALIFICACION INT,
    COMENTARIO TEXT,
    FECHA_COMENTARIO DATETIME DEFAULT CURRENT_TIMESTAMP,
    ID_ESTADO INT,
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO_TB(ID_PRODUCTO),
    FOREIGN KEY (IDENTIFICACION) REFERENCES USUARIO_TB(IDENTIFICACION),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO_TB(ID_ESTADO)
);

-- ==============================
-- MODULO INVENTARIO
-- ==============================

CREATE TABLE INVENTARIO_TB (
    ID_INVENTARIO INT AUTO_INCREMENT PRIMARY KEY,
    ID_PRODUCTO INT UNIQUE,
    STOCK INT,
    ID_ESTADO INT,
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO_TB(ID_PRODUCTO),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO_TB(ID_ESTADO)
);

CREATE TABLE TIPO_MOVIMIENTO_TB (
    ID_TIPO_MOVIMIENTO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100),
    ID_ESTADO INT,
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO_TB(ID_ESTADO)
);

CREATE TABLE MOVIMIENTO_INVENTARIO_TB (
    ID_MOVIMIENTO INT AUTO_INCREMENT PRIMARY KEY,
    ID_PRODUCTO INT,
    ID_TIPO_MOVIMIENTO INT,
    CANTIDAD INT,
    MOTIVO TEXT,
    FECHA_MOVIMIENTO DATETIME DEFAULT CURRENT_TIMESTAMP,
    ID_ESTADO INT,
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO_TB(ID_PRODUCTO),
    FOREIGN KEY (ID_TIPO_MOVIMIENTO) REFERENCES TIPO_MOVIMIENTO_TB(ID_TIPO_MOVIMIENTO),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO_TB(ID_ESTADO)
);

-- ==============================
-- MODULO CARRITO
-- ==============================

CREATE TABLE CARRITO_TB (
    ID_CARRITO INT AUTO_INCREMENT PRIMARY KEY,
    ID_CUENTA INT,
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    ID_ESTADO INT,
    FOREIGN KEY (ID_CUENTA) REFERENCES CUENTA_TB(ID_CUENTA),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO_TB(ID_ESTADO)
);

CREATE TABLE CARRITO_ITEM_TB (
    ID_CARRITO INT,
    ID_PRODUCTO INT,
    CANTIDAD INT,
    PRIMARY KEY (ID_CARRITO, ID_PRODUCTO),
    FOREIGN KEY (ID_CARRITO) REFERENCES CARRITO_TB(ID_CARRITO),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO_TB(ID_PRODUCTO)
);


-- ==============================
-- MODULO VENTA
-- ==============================
CREATE TABLE VENTA_TB (
    ID_VENTA INT AUTO_INCREMENT PRIMARY KEY,
    ID_CUENTA INT,
    FECHA_VENTA DATETIME DEFAULT CURRENT_TIMESTAMP,
    ID_ESTADO INT,
    FOREIGN KEY (ID_CUENTA) REFERENCES CUENTA_TB(ID_CUENTA),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO_TB(ID_ESTADO)
);

CREATE TABLE VENTA_PRODUCTO_TB(
    ID_VENTA INT,
    ID_PRODUCTO INT,
    CANTIDAD INT,
    PRECIO DECIMAL(10,2),
    PRIMARY KEY (ID_VENTA, ID_PRODUCTO),
    FOREIGN KEY (ID_VENTA) REFERENCES VENTA_TB(ID_VENTA),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO_TB(ID_PRODUCTO)

);

-- ==============================
-- MODULO FACTURACION
-- ==============================

CREATE TABLE FACTURA_TB (
    ID_FACTURA INT AUTO_INCREMENT PRIMARY KEY,
    ID_VENTA INT,
    IMPUESTO DECIMAL(5,2),
    SUBTOTAL DECIMAL(10,2),
    TOTAL DECIMAL(10,2),
    FECHA_FACTURA DATETIME DEFAULT CURRENT_TIMESTAMP,
    ID_ESTADO INT,
    FOREIGN KEY (ID_VENTA) REFERENCES VENTA_TB(ID_VENTA),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO_TB(ID_ESTADO)
);


-- ==============================
-- MODULO PROMOCIONES
-- ==============================

CREATE TABLE PROMOCION_TB (
    ID_PROMOCION INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(150),
    DESCRIPCION TEXT,
    PORCENTAJE DECIMAL(5,2),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    ID_ESTADO INT,
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO_TB(ID_ESTADO)
);

CREATE TABLE PROMOCION_PRODUCTO_TB (
    ID_PROMOCION INT,
    ID_PRODUCTO INT,
    ID_ESTADO INT,
    PRIMARY KEY (ID_PROMOCION, ID_PRODUCTO),
    FOREIGN KEY (ID_PROMOCION) REFERENCES PROMOCION_TB(ID_PROMOCION),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO_TB(ID_PRODUCTO),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO_TB(ID_ESTADO)
);

CREATE TABLE CUPON_DESCUENTO_TB (
    ID_CUPON INT AUTO_INCREMENT PRIMARY KEY,
    CODIGO VARCHAR(50),
    PORCENTAJE DECIMAL(5,2),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    USO_MAXIMO INT,
    ID_ESTADO INT,
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO_TB(ID_ESTADO)
);

-- ==============================
-- MODULO PAGOS
-- ==============================

CREATE TABLE MONEDA_TB (
    ID_MONEDA INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50),
    ID_ESTADO INT,
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO_TB(ID_ESTADO)
);

CREATE TABLE PAGO_PAYPAL_TB (
    ID_PAGO INT AUTO_INCREMENT PRIMARY KEY,
    ID_FACTURA INT,
    PAYPAL_ORDER_ID VARCHAR(150),
    PAYPAL_CAPTURE_ID VARCHAR(150),
    TOTAL DECIMAL(10,2),
    ID_MONEDA INT,
    FECHA_REGISTRO DATETIME DEFAULT CURRENT_TIMESTAMP,
    ID_ESTADO INT,
    FOREIGN KEY (ID_FACTURA) REFERENCES FACTURA_TB(ID_FACTURA),
    FOREIGN KEY (ID_MONEDA) REFERENCES MONEDA_TB(ID_MONEDA),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO_TB(ID_ESTADO)
);

-- ==============================
-- MODULO SEGURIDAD
-- ==============================

CREATE TABLE REFRESH_TOKEN_TB (
    ID_REFRESH_TOKEN INT AUTO_INCREMENT PRIMARY KEY,
    ID_CUENTA INT,
    TOKEN_HASH VARCHAR(255),
    JTI VARCHAR(100),
    ISSUED_AT DATETIME,
    EXPIRES_AT DATETIME,
    REVOKED_AT DATETIME,
    IP VARCHAR(50),
    USER_AGENT TEXT,
    ID_ESTADO INT,
    FOREIGN KEY (ID_CUENTA) REFERENCES CUENTA_TB(ID_CUENTA),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO_TB(ID_ESTADO)
);

CREATE TABLE TIPO_OTP_TB (
    ID_TIPO_OTP INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100),
    ID_ESTADO INT,
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO_TB(ID_ESTADO)
);

CREATE TABLE CODIGO_OTP_TB (
    OTP_CODE VARCHAR(20),
    ID_CUENTA INT,
    ID_TIPO_OTP INT,
    HASH VARCHAR(255),
    EXPIRES_AT DATETIME,
    INTENTOS INT,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    ACTIVE_FLAG BOOLEAN,
    ID_ESTADO INT,
    PRIMARY KEY (OTP_CODE, ID_CUENTA),
    FOREIGN KEY (ID_CUENTA) REFERENCES CUENTA_TB(ID_CUENTA),
    FOREIGN KEY (ID_TIPO_OTP) REFERENCES TIPO_OTP_TB(ID_TIPO_OTP),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO_TB(ID_ESTADO)
);

-- ==============================
-- MODULO AUDITORIA
-- ==============================

CREATE TABLE AUDITORIA_TB (
    ID_AUDITORIA INT AUTO_INCREMENT PRIMARY KEY,
    ACCION VARCHAR(50),
    TABLA_AFECTADA VARCHAR(100),
    FECHA DATETIME DEFAULT CURRENT_TIMESTAMP,
    IDENTIFICACION VARCHAR(20),
    ID_ESTADO INT,
    FOREIGN KEY (IDENTIFICACION) REFERENCES USUARIO_TB(IDENTIFICACION),
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO_TB(ID_ESTADO)
);